# Generated by Django 4.0.4 on 2022-06-11 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_classname_remove_student_status_student_monthly_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.classname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.classname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='monthly_fee',
            field=models.IntegerField(),
        ),
    ]
